lexik_jwt_authentication:
    secret_key: '%env(JWT_SECRET)%'
    encoder:
        service: lexik_jwt_authentication.encoder.lcobucci
    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
        cookie:
            enabled: false
        query_parameter:
            enabled: false
            name: bearer
    token_ttl: 3600
    user_identity_field: email
